# Generated by Django 3.2 on 2021-04-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('meta_score', models.IntegerField()),
                ('gameDesc', models.CharField(max_length=50)),
                ('user_score', models.FloatField()),
                ('age_rating', models.CharField(max_length=50)),
                ('Devs', models.CharField(max_length=50)),
                ('Genres', models.CharField(max_length=50)),
                ('weighed_score', models.FloatField()),
            ],
        ),
    ]
