# Generated by Django 3.2 on 2021-05-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='games',
            name='gameDesc',
            field=models.CharField(max_length=10000),
        ),
    ]
